cc_binary(
  name = 'tcp_server',
  srcs = [
    'tcp_server.cc',
  ],
  deps = [
    ':addr',
  ],
)

cc_binary(
  name = 'tcp_client',
  srcs = [
    'tcp_client.cc',
  ],
  deps = [
    ':addr',
  ],
)

cc_library(
  name = 'addr',
  hdrs = [
    'addr.h',
  ],
  srcs = [
    'addr.cc',
  ],
)
